config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  resources :products do
    resources :variants
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :variants, dependent: :destroy
  accepts_nested_attributes_for :variants, allow_destroy: true
  validates :description, length: { maximum: 300 }
  validates :title, presence: true
  default_scope { where.not(soft_deleted: true) }
end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :product
  validates :sku, uniqueness: true, presence: true
  validates :stock_quantity, presence: true, :numericality => { :greater_than => 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def dashboard
    @products = Product.all

  end
  def products
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, only: [:update, :destroy]
  
  def index
    @products = Product.all.order('created_at DESC')
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @product.variants.build

  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product.update(product_params)
    redirect_to products_path
  end

  def destroy
    @product.update(soft_deleted: true)
    redirect_to products_path
  end

  def load_product
    @product = Product.find(params[:id])
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, variants_attributes: [:sku, :stock_quantity, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Warehouse Software</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'%>
    <%= javascript_tag 'application' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <div class="container d-flex p-5">
      <h1 class="pr-2"><%= link_to "Dashboard", dashboard_path %> | </h1>
      <h1><%= link_to "Products", products_path %></h1>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>Dashboard</h1>
<h3>Products created stats</h3>
<p>Last 24 hours</p>
<%= line_chart Product.group_by_hour(:created_at).count %>
<p>Last 7 days</p>
<%= line_chart Product.group_by_day(:created_at).count %>

app/views/pages/products.html.erb
<h1>New Product</h1>
<ul>
  <% @products.each do |product| %>
    <li><%= product.title %></li>
    <p><%= product.description%></p>
    <%= link_to 'Edit', edit_product_path(product) %> |
    <%= link_to 'Delete', soft_delete_product_path(product) %> |

  <% end %>
</ul>
<form action="/products" method="get">
  <input type="text" name="title" placeholder="nice product">
    <input type="text" name="description" placeholder="Awesome description">
  <input type="submit">
</form>

app/views/products/_form.html.erb
<div class="">
  <%= simple_form_for @product do |product| %>
    <%= product.input :title %>
    <%= product.input :description,:label => "Descripton (max 300 characters)", as: :text, maxlength: true %>
      <div class="d-flex justify-content-between align-items-center">
        <h3>Variants</h3>
        <button type="button" class="btn btn-primary" id="new_variant_btn" >Add new variant</button>
      </div>
      <div id="variant_parent">
      <div id="variant_form">
        <%= product.simple_fields_for :variants do |v| %>
        <%= v.input :sku %>
        <%= v.input :stock_quantity %>
        <button type="button" class="delete_variant_btn btn btn-primary mb-5">Delete variant</button>
        <% end %>
      </div>
      </div>
    <%= product.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render "form", product: @product %>

app/views/products/index.html.erb
<div class="w-50 d-flex justify-content-between align-items-center pb-5">
<h1>Products</h1>
    <%= link_to 'Add product', new_product_path, class: "btn btn-primary ml-5" %>
</div>
  <% @products.each do |product| %>
  <div class="w-50 d-flex align-items-center justify-content-between">
    <h4><%= product.title %></h4>
    <% product.variants.each do |variant| %>
    <%=variant.stock_quantity%> in stock
    <%end%>
      <div class="">
        <%= link_to 'Edit', edit_product_path(product), class: "btn btn-primary ml-5"  %>
        <%= link_to "Delete",
                  product_path(product),
                  method: :delete,
                  data: { confirm: "Are you sure you want to delete ?" },class: "btn btn-primary ml-5"  %>
    </div>
  </div>
  <p><%= product.description%></p>

<p>_________________________________________________________________________</p>
  <% end %>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render "form", product: @product %>